import { MigrationInterface, QueryRunner } from "typeorm";

export class CreateAllTables1779850685448 implements MigrationInterface {
    name = 'CreateAllTables1779850685448'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "services" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "client_name" character varying(200) NOT NULL, "client_email" character varying, "client_phone" character varying(20), "address" text NOT NULL, "latitude" numeric(10,7), "longitude" numeric(10,7), "access_instructions" text, "service_type" character varying(100) NOT NULL, "custom_service_type" character varying(100), "status" "public"."services_status_enum" NOT NULL DEFAULT 'scheduled', "scheduled_at" TIMESTAMP NOT NULL, "estimated_minutes" integer NOT NULL, "special_instructions" text, "checklist_template_id" character varying, "cancellation_reason" text, "cancelled_at" TIMESTAMP, "cancelled_by" character varying, "needs_review_reason" text, "has_incidents" boolean NOT NULL DEFAULT false, "is_checklist_complete" boolean NOT NULL DEFAULT true, "parent_service_id" uuid, "recurrence_rule" character varying(20), "recurrence_end_date" TIMESTAMP, "recurrence_instance" integer, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_ba2d347a3168a296416c6c5ccb2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_1571d214bb00fbca0ff56b2fc4" ON "services" ("status", "scheduled_at") `);
        await queryRunner.query(`CREATE TABLE "checklist_templates" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(200) NOT NULL, "description" text, "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_e6d17651d110bbac45cf07e44fa" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "checklist_template_items" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "template_id" uuid NOT NULL, "label" character varying(300) NOT NULL, "order" integer NOT NULL DEFAULT '0', "required" boolean NOT NULL DEFAULT false, "requires_photo" boolean NOT NULL DEFAULT false, "max_photos" integer NOT NULL DEFAULT '5', "category" character varying(100), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_27f7e6351f6748a0c3053d4b97a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_5bb7b906bd14e71ddbf7226d85" ON "checklist_template_items" ("template_id", "order") `);
        await queryRunner.query(`CREATE TABLE "service_checklist_items" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "assignment_id" uuid NOT NULL, "template_item_id" uuid NOT NULL, "status" "public"."service_checklist_items_status_enum" NOT NULL DEFAULT 'pending', "completed_at" TIMESTAMP, "completed_by" character varying, "notes" text, "photo_id" character varying, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_c94287714b07bce4ca18b770faa" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_8c48224011cda0b0a13754f98c" ON "service_checklist_items" ("assignment_id", "template_item_id") `);
        await queryRunner.query(`CREATE TABLE "photos" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "assignment_id" uuid NOT NULL, "service_id" character varying, "checklist_item_id" character varying, "uploaded_by" uuid NOT NULL, "category" "public"."photos_category_enum" NOT NULL, "type" character varying(50), "status" "public"."photos_status_enum" NOT NULL DEFAULT 'pending', "filename" character varying(500) NOT NULL, "original_name" character varying(500) NOT NULL, "mime_type" character varying(100) NOT NULL, "size" integer NOT NULL, "file_path" character varying, "file_size_kb" numeric(10,2), "compressed_size" integer, "url" character varying, "thumbnail_url" character varying, "latitude" numeric(10,7), "longitude" numeric(10,7), "taken_at" TIMESTAMP, "uploaded_at" TIMESTAMP, "is_synced" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_5220c45b8e32d49d767b9b3d725" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_92ef64d1c59fa6521eec77e412" ON "photos" ("service_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_69aa751ce254fbf960f6da3b08" ON "photos" ("assignment_id", "category") `);
        await queryRunner.query(`CREATE TABLE "location_logs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "assignment_id" uuid, "latitude" numeric(10,7) NOT NULL, "longitude" numeric(10,7) NOT NULL, "accuracy" numeric(5,2), "timestamp" TIMESTAMP NOT NULL, "is_within_radius" boolean, "is_synced" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_f61ffb8ec1e177e99dcd82669bc" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_f52bfe245c444f97839b2f8c1e" ON "location_logs" ("timestamp") `);
        await queryRunner.query(`CREATE INDEX "IDX_7ed406b8dca9059927aac34e45" ON "location_logs" ("user_id", "assignment_id") `);
        await queryRunner.query(`CREATE TABLE "location_alerts" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "assignment_id" uuid NOT NULL, "type" "public"."location_alerts_type_enum" NOT NULL, "latitude" numeric(10,7) NOT NULL, "longitude" numeric(10,7) NOT NULL, "expected_latitude" numeric(10,7) NOT NULL, "expected_longitude" numeric(10,7) NOT NULL, "distance" numeric(10,2) NOT NULL, "resolved" boolean NOT NULL DEFAULT false, "grace_ends_at" TIMESTAMP, "alert_sent_at" TIMESTAMP, "reviewed_by" character varying, "reviewed_at" TIMESTAMP, "resolved_at" TIMESTAMP, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_19d3e4078143c97bef9fe181591" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_f537b580f854ee156c16cce989" ON "location_alerts" ("resolved") `);
        await queryRunner.query(`CREATE INDEX "IDX_4e94f34565f12b30eafbe70c16" ON "location_alerts" ("user_id", "assignment_id") `);
        await queryRunner.query(`CREATE TABLE "service_assignments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "service_id" uuid NOT NULL, "cleaner_id" uuid NOT NULL, "scheduled_date" date NOT NULL, "scheduled_start_time" TIME NOT NULL, "scheduled_end_time" TIME NOT NULL, "status" "public"."service_assignments_status_enum" NOT NULL DEFAULT 'pending', "timer_start" TIMESTAMP, "timer_end" TIMESTAMP, "total_minutes" integer, "hourly_rate_snapshot" numeric(10,2), "payment_calculated" numeric(10,2), "notes" text, "started_at" TIMESTAMP, "completed_at" TIMESTAMP, "latitude" numeric(10,7), "longitude" numeric(10,7), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_58c88200d9341fecdd9a9375347" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_d36a5aeb80d0d7370cb445076e" ON "service_assignments" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_cdbdbd39db62a610ccb0eb9c15" ON "service_assignments" ("cleaner_id", "scheduled_date") `);
        await queryRunner.query(`CREATE TABLE "notifications" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "recipient_id" character varying, "type" "public"."notifications_type_enum" NOT NULL, "title" character varying(200) NOT NULL, "body" text NOT NULL, "data" jsonb, "related_service_id" character varying, "related_alert_id" character varying, "read" boolean NOT NULL DEFAULT false, "read_at" TIMESTAMP, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_6a72c3c0f683f6462415e653c3a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_5332a4daa46fd3f4e6625dd275" ON "notifications" ("recipient_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_a17edcb3b8e39c52a7d0554d31" ON "notifications" ("user_id", "read") `);
        await queryRunner.query(`CREATE TABLE "documents" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "category" "public"."documents_category_enum" NOT NULL, "filename" character varying(500) NOT NULL, "original_name" character varying(500) NOT NULL, "mime_type" character varying(100) NOT NULL, "size" integer NOT NULL, "url" character varying NOT NULL, "uploaded_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_ac51aa5181ee2036f5ca482857c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_b20c1ae2c7098e9a822f15aa6f" ON "documents" ("category") `);
        await queryRunner.query(`CREATE INDEX "IDX_c7481daf5059307842edef74d7" ON "documents" ("user_id") `);
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "email" character varying NOT NULL, "password_hash" character varying NOT NULL, "first_name" character varying(50) NOT NULL, "last_name" character varying(50) NOT NULL, "phone" character varying(20), "role" "public"."users_role_enum" NOT NULL, "is_active" boolean NOT NULL DEFAULT true, "photo_url" character varying, "language" character varying(10) NOT NULL DEFAULT 'en', "hourly_rate" numeric(10,2), "contract_type" "public"."users_contract_type_enum", "must_change_password" boolean NOT NULL DEFAULT false, "created_by" character varying, "refreshToken" text, "reset_password_token" text, "reset_password_expires" TIMESTAMP, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_97672ac88f789774dd47f7c8be" ON "users" ("email") `);
        await queryRunner.query(`CREATE TABLE "offline_sync_queue" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" character varying NOT NULL, "entity" "public"."offline_sync_queue_entity_enum" NOT NULL, "entity_id" character varying NOT NULL, "action" "public"."offline_sync_queue_action_enum" NOT NULL, "payload" jsonb NOT NULL, "status" "public"."offline_sync_queue_status_enum" NOT NULL DEFAULT 'pending', "retry_count" integer NOT NULL DEFAULT '0', "error" text, "processed_at" TIMESTAMP, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_40d6a4ca8795a28bf1e71cdea6a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_911397385e937207e709ac87a9" ON "offline_sync_queue" ("created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_7a6711972332a48033523ac12a" ON "offline_sync_queue" ("user_id", "status") `);
        await queryRunner.query(`CREATE TABLE "time_records" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "assignment_id" uuid NOT NULL, "user_id" uuid NOT NULL, "type" "public"."time_records_type_enum" NOT NULL, "latitude" numeric(10,7), "longitude" numeric(10,7), "accuracy" numeric(5,2), "timestamp" TIMESTAMP NOT NULL, "is_within_radius" boolean, "geofence_radius" integer NOT NULL DEFAULT '200', "distance_from_service" numeric(10,2), "approval_status" "public"."time_records_approval_status_enum" NOT NULL DEFAULT 'pending', "approved_by" character varying, "approved_at" TIMESTAMP, "adjusted_minutes" integer, "adjustment_reason" text, "inconsistencies" jsonb, "is_synced" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_0d2985ead4ba3604143eee43f90" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_80234c4809d0812ce9e8d0e7a2" ON "time_records" ("approval_status") `);
        await queryRunner.query(`CREATE INDEX "IDX_7fed91e92e099e6614128bf8cf" ON "time_records" ("timestamp") `);
        await queryRunner.query(`CREATE INDEX "IDX_fb2964973c63498acb1a046070" ON "time_records" ("assignment_id", "type") `);
        await queryRunner.query(`CREATE INDEX "IDX_97e8ba23367d50e9ba7f51558f" ON "time_records" ("user_id", "assignment_id") `);
        await queryRunner.query(`CREATE TABLE "service_types" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(100) NOT NULL, "category" character varying(50), "is_active" boolean NOT NULL DEFAULT true, "is_custom" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_1dc93417a097cdee3491f39d7cc" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "reports" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "type" "public"."reports_type_enum" NOT NULL, "format" "public"."reports_format_enum" NOT NULL, "generated_by" character varying NOT NULL, "url" character varying, "file_path_pdf" character varying, "file_path_xlsx" character varying, "filename" character varying(500) NOT NULL, "date_from" date NOT NULL, "date_to" date NOT NULL, "metadata" jsonb, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_d9013193989303580053c0b5ef6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_a6e7ed3fa4204bc87561fe99eb" ON "reports" ("type", "created_at") `);
        await queryRunner.query(`CREATE TABLE "performance_scores" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "contractor_id" uuid NOT NULL, "period" "public"."performance_scores_period_enum" NOT NULL, "period_start" date NOT NULL, "period_end" date NOT NULL, "attendance_rate" numeric(5,2) NOT NULL DEFAULT '0', "punctuality_rate" numeric(5,2) NOT NULL DEFAULT '0', "avg_time_variance" numeric(5,2), "quality_score" numeric(5,2) NOT NULL DEFAULT '0', "checklist_completion_rate" numeric(5,2) NOT NULL DEFAULT '0', "incident_count" integer NOT NULL DEFAULT '0', "services_completed" integer NOT NULL DEFAULT '0', "total_hours" numeric(10,2) NOT NULL DEFAULT '0', "avg_evaluation_score" numeric(4,2), "evaluation_count" integer NOT NULL DEFAULT '0', "details" jsonb, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_7b87c8602302daf92a14db1be62" UNIQUE ("contractor_id", "period", "period_start"), CONSTRAINT "PK_0fe963501e0d7633b11e3c535de" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_9e0d2ea4180223035ddcb17cd4" ON "performance_scores" ("period", "period_start") `);
        await queryRunner.query(`CREATE INDEX "IDX_0f2477a035fdc35de7ebe81deb" ON "performance_scores" ("contractor_id", "period") `);
        await queryRunner.query(`CREATE TABLE "push_subscriptions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "endpoint" text NOT NULL, "p256dh" character varying NOT NULL, "auth" character varying NOT NULL, "user_agent" character varying, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_757fc8f00c34f66832668dc2e53" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_6771f119f1c06d2ccf38f23866" ON "push_subscriptions" ("user_id") `);
        await queryRunner.query(`CREATE TABLE "supervisor_evaluations" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "contractor_id" uuid NOT NULL, "assignment_id" uuid NOT NULL, "evaluated_by" uuid NOT NULL, "score" integer NOT NULL, "comment" text, "service_type" character varying(100), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_54fd392d12cb2ea3b11336c98f8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_0a6c8b8e9c0b04f69fe6584973" ON "supervisor_evaluations" ("evaluated_by") `);
        await queryRunner.query(`CREATE INDEX "IDX_dd909133b0de4b25b36a1c6193" ON "supervisor_evaluations" ("assignment_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_260656b454f87daef76627537d" ON "supervisor_evaluations" ("contractor_id") `);
        await queryRunner.query(`CREATE TABLE "inventory_transactions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "supply_item_id" uuid NOT NULL, "type" "public"."inventory_transactions_type_enum" NOT NULL, "quantity" numeric(10,2) NOT NULL, "previous_stock" numeric(10,2) NOT NULL, "new_stock" numeric(10,2) NOT NULL, "reference" character varying(200), "service_id" uuid, "contractor_id" uuid, "notes" text, "created_by" character varying NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_9b7144851f08f9eededde7edd42" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_60abd2351984e1f825f1fcab31" ON "inventory_transactions" ("created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_29f2febec89b8d0a54d1cc3b75" ON "inventory_transactions" ("contractor_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_ecb0ff1967f2116f2ce131c725" ON "inventory_transactions" ("service_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_4c7b1eba9aa101c0411ef09cd9" ON "inventory_transactions" ("supply_item_id") `);
        await queryRunner.query(`CREATE TABLE "supply_items" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(200) NOT NULL, "category" "public"."supply_items_category_enum" NOT NULL, "unit_of_measure" character varying(50) NOT NULL, "stock_min" integer NOT NULL DEFAULT '5', "current_stock" numeric(10,2) NOT NULL DEFAULT '0', "supplier" character varying(200), "sku" character varying(100), "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_b2fb72ee1259b3531157e60bdc8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_98c9ca8987121c5a41e47d5b64" ON "supply_items" ("is_active") `);
        await queryRunner.query(`CREATE INDEX "IDX_4d12c91bad88281703b2dea8c5" ON "supply_items" ("category") `);
        await queryRunner.query(`CREATE TABLE "incidents" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "assignment_id" uuid NOT NULL, "reported_by" uuid NOT NULL, "title" character varying(300) NOT NULL, "description" text NOT NULL, "status" "public"."incidents_status_enum" NOT NULL DEFAULT 'open', "severity" "public"."incidents_severity_enum" NOT NULL DEFAULT 'low', "photo_urls" json, "resolved_by" character varying, "resolved_at" TIMESTAMP, "resolution_notes" text, "reviewed_by" character varying, "reviewed_at" TIMESTAMP, "is_synced" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_ccb34c01719889017e2246469f9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_3ebe443aa45fa27fd71ed165e0" ON "incidents" ("reported_by") `);
        await queryRunner.query(`CREATE INDEX "IDX_113813a83d947f64e6d5458100" ON "incidents" ("assignment_id", "status") `);
        await queryRunner.query(`CREATE TABLE "audit_logs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" character varying, "action" "public"."audit_logs_action_enum" NOT NULL, "entity_type" character varying(100) NOT NULL, "entity_id" character varying, "old_values" json, "new_values" json, "ip_address" character varying(45), "user_agent" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_1bb179d048bbc581caa3b013439" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_2cd10fda8276bb995288acfbfb" ON "audit_logs" ("created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_bd2726fd31b35443f2245b93ba" ON "audit_logs" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_7421efc125d95e413657efa3c6" ON "audit_logs" ("entity_type", "entity_id") `);
        await queryRunner.query(`ALTER TABLE "services" ADD CONSTRAINT "FK_e461db34d6e4d5ddfd90ec228f6" FOREIGN KEY ("parent_service_id") REFERENCES "services"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "checklist_template_items" ADD CONSTRAINT "FK_5de6eeebd7ffec3fdf257ff21be" FOREIGN KEY ("template_id") REFERENCES "checklist_templates"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "service_checklist_items" ADD CONSTRAINT "FK_1a36070ec5a663d8edae479646b" FOREIGN KEY ("assignment_id") REFERENCES "service_assignments"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "service_checklist_items" ADD CONSTRAINT "FK_30ea9cc4d14958de69a7e22e7b5" FOREIGN KEY ("template_item_id") REFERENCES "checklist_template_items"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "photos" ADD CONSTRAINT "FK_592e7ce4fece326cda0833e674b" FOREIGN KEY ("assignment_id") REFERENCES "service_assignments"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "photos" ADD CONSTRAINT "FK_321fd52a2c7d768cf387257e198" FOREIGN KEY ("uploaded_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "location_logs" ADD CONSTRAINT "FK_986f3d5f153f0575e0e98fbf00a" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "location_logs" ADD CONSTRAINT "FK_c3b2ac9f73ed398acefa4bd5012" FOREIGN KEY ("assignment_id") REFERENCES "service_assignments"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "location_alerts" ADD CONSTRAINT "FK_bfc2a1b8942ba5e6c12e6a93c63" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "location_alerts" ADD CONSTRAINT "FK_b78fc33eb9d2955fc6312680b14" FOREIGN KEY ("assignment_id") REFERENCES "service_assignments"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "service_assignments" ADD CONSTRAINT "FK_86fcb93a40f49ac8e625495c196" FOREIGN KEY ("cleaner_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "service_assignments" ADD CONSTRAINT "FK_7eb4fa44ac22ad1f74f38a3a5c6" FOREIGN KEY ("service_id") REFERENCES "services"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "FK_9a8a82462cab47c73d25f49261f" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "documents" ADD CONSTRAINT "FK_c7481daf5059307842edef74d73" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "time_records" ADD CONSTRAINT "FK_0149b95adf0ce34734ed1e11e93" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "time_records" ADD CONSTRAINT "FK_6b694ae5a33c8ee33a05ffe7729" FOREIGN KEY ("assignment_id") REFERENCES "service_assignments"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "performance_scores" ADD CONSTRAINT "FK_bbe4219c274482f9e9f817335c3" FOREIGN KEY ("contractor_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "push_subscriptions" ADD CONSTRAINT "FK_6771f119f1c06d2ccf38f238664" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "supervisor_evaluations" ADD CONSTRAINT "FK_260656b454f87daef76627537d4" FOREIGN KEY ("contractor_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "supervisor_evaluations" ADD CONSTRAINT "FK_0a6c8b8e9c0b04f69fe65849730" FOREIGN KEY ("evaluated_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "supervisor_evaluations" ADD CONSTRAINT "FK_dd909133b0de4b25b36a1c6193c" FOREIGN KEY ("assignment_id") REFERENCES "service_assignments"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory_transactions" ADD CONSTRAINT "FK_4c7b1eba9aa101c0411ef09cd91" FOREIGN KEY ("supply_item_id") REFERENCES "supply_items"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory_transactions" ADD CONSTRAINT "FK_ecb0ff1967f2116f2ce131c7255" FOREIGN KEY ("service_id") REFERENCES "services"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory_transactions" ADD CONSTRAINT "FK_29f2febec89b8d0a54d1cc3b75f" FOREIGN KEY ("contractor_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "incidents" ADD CONSTRAINT "FK_3ebe443aa45fa27fd71ed165e04" FOREIGN KEY ("reported_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "incidents" ADD CONSTRAINT "FK_afbba1e7f35217320d0fb0fe9ff" FOREIGN KEY ("assignment_id") REFERENCES "service_assignments"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "incidents" DROP CONSTRAINT "FK_afbba1e7f35217320d0fb0fe9ff"`);
        await queryRunner.query(`ALTER TABLE "incidents" DROP CONSTRAINT "FK_3ebe443aa45fa27fd71ed165e04"`);
        await queryRunner.query(`ALTER TABLE "inventory_transactions" DROP CONSTRAINT "FK_29f2febec89b8d0a54d1cc3b75f"`);
        await queryRunner.query(`ALTER TABLE "inventory_transactions" DROP CONSTRAINT "FK_ecb0ff1967f2116f2ce131c7255"`);
        await queryRunner.query(`ALTER TABLE "inventory_transactions" DROP CONSTRAINT "FK_4c7b1eba9aa101c0411ef09cd91"`);
        await queryRunner.query(`ALTER TABLE "supervisor_evaluations" DROP CONSTRAINT "FK_dd909133b0de4b25b36a1c6193c"`);
        await queryRunner.query(`ALTER TABLE "supervisor_evaluations" DROP CONSTRAINT "FK_0a6c8b8e9c0b04f69fe65849730"`);
        await queryRunner.query(`ALTER TABLE "supervisor_evaluations" DROP CONSTRAINT "FK_260656b454f87daef76627537d4"`);
        await queryRunner.query(`ALTER TABLE "push_subscriptions" DROP CONSTRAINT "FK_6771f119f1c06d2ccf38f238664"`);
        await queryRunner.query(`ALTER TABLE "performance_scores" DROP CONSTRAINT "FK_bbe4219c274482f9e9f817335c3"`);
        await queryRunner.query(`ALTER TABLE "time_records" DROP CONSTRAINT "FK_6b694ae5a33c8ee33a05ffe7729"`);
        await queryRunner.query(`ALTER TABLE "time_records" DROP CONSTRAINT "FK_0149b95adf0ce34734ed1e11e93"`);
        await queryRunner.query(`ALTER TABLE "documents" DROP CONSTRAINT "FK_c7481daf5059307842edef74d73"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "FK_9a8a82462cab47c73d25f49261f"`);
        await queryRunner.query(`ALTER TABLE "service_assignments" DROP CONSTRAINT "FK_7eb4fa44ac22ad1f74f38a3a5c6"`);
        await queryRunner.query(`ALTER TABLE "service_assignments" DROP CONSTRAINT "FK_86fcb93a40f49ac8e625495c196"`);
        await queryRunner.query(`ALTER TABLE "location_alerts" DROP CONSTRAINT "FK_b78fc33eb9d2955fc6312680b14"`);
        await queryRunner.query(`ALTER TABLE "location_alerts" DROP CONSTRAINT "FK_bfc2a1b8942ba5e6c12e6a93c63"`);
        await queryRunner.query(`ALTER TABLE "location_logs" DROP CONSTRAINT "FK_c3b2ac9f73ed398acefa4bd5012"`);
        await queryRunner.query(`ALTER TABLE "location_logs" DROP CONSTRAINT "FK_986f3d5f153f0575e0e98fbf00a"`);
        await queryRunner.query(`ALTER TABLE "photos" DROP CONSTRAINT "FK_321fd52a2c7d768cf387257e198"`);
        await queryRunner.query(`ALTER TABLE "photos" DROP CONSTRAINT "FK_592e7ce4fece326cda0833e674b"`);
        await queryRunner.query(`ALTER TABLE "service_checklist_items" DROP CONSTRAINT "FK_30ea9cc4d14958de69a7e22e7b5"`);
        await queryRunner.query(`ALTER TABLE "service_checklist_items" DROP CONSTRAINT "FK_1a36070ec5a663d8edae479646b"`);
        await queryRunner.query(`ALTER TABLE "checklist_template_items" DROP CONSTRAINT "FK_5de6eeebd7ffec3fdf257ff21be"`);
        await queryRunner.query(`ALTER TABLE "services" DROP CONSTRAINT "FK_e461db34d6e4d5ddfd90ec228f6"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7421efc125d95e413657efa3c6"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bd2726fd31b35443f2245b93ba"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2cd10fda8276bb995288acfbfb"`);
        await queryRunner.query(`DROP TABLE "audit_logs"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_113813a83d947f64e6d5458100"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3ebe443aa45fa27fd71ed165e0"`);
        await queryRunner.query(`DROP TABLE "incidents"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4d12c91bad88281703b2dea8c5"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_98c9ca8987121c5a41e47d5b64"`);
        await queryRunner.query(`DROP TABLE "supply_items"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4c7b1eba9aa101c0411ef09cd9"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ecb0ff1967f2116f2ce131c725"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_29f2febec89b8d0a54d1cc3b75"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_60abd2351984e1f825f1fcab31"`);
        await queryRunner.query(`DROP TABLE "inventory_transactions"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_260656b454f87daef76627537d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_dd909133b0de4b25b36a1c6193"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0a6c8b8e9c0b04f69fe6584973"`);
        await queryRunner.query(`DROP TABLE "supervisor_evaluations"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6771f119f1c06d2ccf38f23866"`);
        await queryRunner.query(`DROP TABLE "push_subscriptions"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0f2477a035fdc35de7ebe81deb"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9e0d2ea4180223035ddcb17cd4"`);
        await queryRunner.query(`DROP TABLE "performance_scores"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a6e7ed3fa4204bc87561fe99eb"`);
        await queryRunner.query(`DROP TABLE "reports"`);
        await queryRunner.query(`DROP TABLE "service_types"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_97e8ba23367d50e9ba7f51558f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fb2964973c63498acb1a046070"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7fed91e92e099e6614128bf8cf"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_80234c4809d0812ce9e8d0e7a2"`);
        await queryRunner.query(`DROP TABLE "time_records"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7a6711972332a48033523ac12a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_911397385e937207e709ac87a9"`);
        await queryRunner.query(`DROP TABLE "offline_sync_queue"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_97672ac88f789774dd47f7c8be"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c7481daf5059307842edef74d7"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b20c1ae2c7098e9a822f15aa6f"`);
        await queryRunner.query(`DROP TABLE "documents"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a17edcb3b8e39c52a7d0554d31"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5332a4daa46fd3f4e6625dd275"`);
        await queryRunner.query(`DROP TABLE "notifications"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cdbdbd39db62a610ccb0eb9c15"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d36a5aeb80d0d7370cb445076e"`);
        await queryRunner.query(`DROP TABLE "service_assignments"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4e94f34565f12b30eafbe70c16"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f537b580f854ee156c16cce989"`);
        await queryRunner.query(`DROP TABLE "location_alerts"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7ed406b8dca9059927aac34e45"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f52bfe245c444f97839b2f8c1e"`);
        await queryRunner.query(`DROP TABLE "location_logs"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_69aa751ce254fbf960f6da3b08"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_92ef64d1c59fa6521eec77e412"`);
        await queryRunner.query(`DROP TABLE "photos"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8c48224011cda0b0a13754f98c"`);
        await queryRunner.query(`DROP TABLE "service_checklist_items"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5bb7b906bd14e71ddbf7226d85"`);
        await queryRunner.query(`DROP TABLE "checklist_template_items"`);
        await queryRunner.query(`DROP TABLE "checklist_templates"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1571d214bb00fbca0ff56b2fc4"`);
        await queryRunner.query(`DROP TABLE "services"`);
    }

}
